### ISSUE TITLE
Fix   "get metric ... --breakout cstype=worker"

### ISSUE THREAD

**Issue by HughNhan** [perftool-incubator/CommonDataModel#109]
In older CDM versions, "--breakout cstype=worker"  was suported.
```
[root@dhcp-10-26-9-216 latest]# crucible get metric --source mpstat --type Busy-CPU --period C501287C-47C5-11EF-9C21-EDF098BAFEDD --breakout cstype=worker
*** NOTICE: Crucible is at least 354 commits behind.  See 'crucible repo info' for details. ***

Checking for httpd...appears to be running
Checking for elasticsearch...appears to be running
Available breakouts:  benchmark-name,benchmark-role,core,csid,cstype,die,endpoint-label,engine-id,engine-role,engine-type,hosted-by,hostname,hypervisor-host,num,osruntime,package,thread,tool-name,type,userenv,benchmark-group                                                                                                               

                               22-07-2024
 source     type cstype=worker   00:58:00
-----------------------------------------
 mpstat Busy-CPU        worker       3.26
```
 Nowaday, it is nolonger supported,,
```
[root@dhcp-10-26-9-237 latest]#  crucible get metric --source mpstat --type Busy-CPU --period C14AD596-453D-11EF-9DFF-A4AF4102E06C --breakout cstype=worker
*** NOTICE: Crucible is at least 10 commits behind.  See 'crucible repo info' for details. ***

Checking for httpd...appears to be running
Checking for OpenSearch...appears to be running
/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/node_modules/http-response-object/lib/index.js:51
            throw err;
            ^

Error: Server responded to http://localhost:9200/cdmv7dev-metric_desc/_msearch with status code 400:
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body or source parameter is required"}],"type":"parse_exception","reason":"request body or source parameter is required"},"status":400}                                                                                                                    
    at Response.getBody (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/node_modules/http-response-object/lib/index.js:41:23)                                                                                                                                                            
    at mgetMetricIdsFromTerms (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/cdm.js:1599:30)
    at getMetricGroupsFromBreakouts (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/cdm.js:1724:31)
    at getMetricDataSets (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/cdm.js:2116:35)
    at Object.getMetricData (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/cdm.js:2049:18)
    at Object.<anonymous> (/opt/crucible/repos/https:github.com:perftool-incubator/CommonDataModel/queries/cdmq/get-metric-data.js:70:19)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  statusCode: 400,
```

**Comment by atheurer** [comment]
We will need to add a new metadata "name", something like "node-type" or reuse an existing one, to replace "cstype".  The reason for this is that the cstype comes from the label of the engine that runs the tools.  When we had all tools combined into one pod for K8S, we would call the engine something like "worker-1".  Since then, these have changed to "profiler-1-sysstat" or something similar, so "worker-1" is not longer in use.
